steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/forward-entity-360908/gcp-test:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/forward-entity-360908gcp-test/gcp-test:$SHORT_SHA']
